package goten

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

type Defaulter interface {
	PopulateDefaults() error
}

type Comparer interface {
	Compare(other interface{}) int
}

// Interface implemented by a Go representation of
// a protobuf message if generated by protoc-gen-goten-go.
type GotenMessage interface {
	fmt.Stringer
	proto.Message
	GotenMessage()
}
