// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.2
// source: goten/annotations/versioning.proto

package versioning

import (
	_ "github.com/cloudwan/goten-sdk/annotations/goten"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceObjectsVersioning_ObjectVersioning_TransformationDirection int32

const (
	ServiceObjectsVersioning_ObjectVersioning_BIDIRECTIONAL   ServiceObjectsVersioning_ObjectVersioning_TransformationDirection = 0
	ServiceObjectsVersioning_ObjectVersioning_FROM_NEW_TO_OLD ServiceObjectsVersioning_ObjectVersioning_TransformationDirection = 1
	ServiceObjectsVersioning_ObjectVersioning_FROM_OLD_TO_NEW ServiceObjectsVersioning_ObjectVersioning_TransformationDirection = 2
	ServiceObjectsVersioning_ObjectVersioning_DISABLED        ServiceObjectsVersioning_ObjectVersioning_TransformationDirection = 3
)

// Enum value maps for ServiceObjectsVersioning_ObjectVersioning_TransformationDirection.
var (
	ServiceObjectsVersioning_ObjectVersioning_TransformationDirection_name = map[int32]string{
		0: "BIDIRECTIONAL",
		1: "FROM_NEW_TO_OLD",
		2: "FROM_OLD_TO_NEW",
		3: "DISABLED",
	}
	ServiceObjectsVersioning_ObjectVersioning_TransformationDirection_value = map[string]int32{
		"BIDIRECTIONAL":   0,
		"FROM_NEW_TO_OLD": 1,
		"FROM_OLD_TO_NEW": 2,
		"DISABLED":        3,
	}
)

func (x ServiceObjectsVersioning_ObjectVersioning_TransformationDirection) Enum() *ServiceObjectsVersioning_ObjectVersioning_TransformationDirection {
	p := new(ServiceObjectsVersioning_ObjectVersioning_TransformationDirection)
	*p = x
	return p
}

func (x ServiceObjectsVersioning_ObjectVersioning_TransformationDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceObjectsVersioning_ObjectVersioning_TransformationDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_goten_annotations_versioning_proto_enumTypes[0].Descriptor()
}

func (ServiceObjectsVersioning_ObjectVersioning_TransformationDirection) Type() protoreflect.EnumType {
	return &file_goten_annotations_versioning_proto_enumTypes[0]
}

func (x ServiceObjectsVersioning_ObjectVersioning_TransformationDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceObjectsVersioning_ObjectVersioning_TransformationDirection.Descriptor instead.
func (ServiceObjectsVersioning_ObjectVersioning_TransformationDirection) EnumDescriptor() ([]byte, []int) {
	return file_goten_annotations_versioning_proto_rawDescGZIP(), []int{0, 1, 0}
}

// ServiceObjectsVersioning contains information about versioning of all
// objects & methods defined in a service package.
type ServiceObjectsVersioning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of all method replacements.
	Methods []*ServiceObjectsVersioning_MethodReplacement `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	// List of all object replacements.
	Objects []*ServiceObjectsVersioning_ObjectVersioning `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *ServiceObjectsVersioning) Reset() {
	*x = ServiceObjectsVersioning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goten_annotations_versioning_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceObjectsVersioning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceObjectsVersioning) ProtoMessage() {}

func (x *ServiceObjectsVersioning) ProtoReflect() protoreflect.Message {
	mi := &file_goten_annotations_versioning_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceObjectsVersioning.ProtoReflect.Descriptor instead.
func (*ServiceObjectsVersioning) Descriptor() ([]byte, []int) {
	return file_goten_annotations_versioning_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceObjectsVersioning) GetMethods() []*ServiceObjectsVersioning_MethodReplacement {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *ServiceObjectsVersioning) GetObjects() []*ServiceObjectsVersioning_ObjectVersioning {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ServiceObjectsVersioning_MethodReplacement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Original method in current service
	// Required format: ${API_NAME}/${METHOD_NAME}, for example:
	// RoleBindingService/GetRoleBinding
	OriginalMethod string `protobuf:"bytes,1,opt,name=original_method,json=originalMethod,proto3" json:"original_method,omitempty"`
	// Replacement method in next version service.
	// Required format: ${API_NAME}/${METHOD_NAME}, for example:
	// RoleBindingService/GetRoleBinding
	Replacement string `protobuf:"bytes,2,opt,name=replacement,proto3" json:"replacement,omitempty"`
}

func (x *ServiceObjectsVersioning_MethodReplacement) Reset() {
	*x = ServiceObjectsVersioning_MethodReplacement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goten_annotations_versioning_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceObjectsVersioning_MethodReplacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceObjectsVersioning_MethodReplacement) ProtoMessage() {}

func (x *ServiceObjectsVersioning_MethodReplacement) ProtoReflect() protoreflect.Message {
	mi := &file_goten_annotations_versioning_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceObjectsVersioning_MethodReplacement.ProtoReflect.Descriptor instead.
func (*ServiceObjectsVersioning_MethodReplacement) Descriptor() ([]byte, []int) {
	return file_goten_annotations_versioning_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceObjectsVersioning_MethodReplacement) GetOriginalMethod() string {
	if x != nil {
		return x.OriginalMethod
	}
	return ""
}

func (x *ServiceObjectsVersioning_MethodReplacement) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

type ServiceObjectsVersioning_ObjectVersioning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Object name, for example "RoleBinding", or request/response like,
	// "CreateRoleBinding". It must exist within current proto package.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Name of the message in the next version.
	// Ignored for a message that is part of an API without next version set.
	// If not provided, then:
	//   - if message this spec describes is "top" message (with no parent message),
	//     then no replacement is assumed.
	//   - if has parent message and that parent message has replacement,
	//     then goten will attempt to find contained message with same name within
	//     replacement for parent.
	Replacement string `protobuf:"bytes,2,opt,name=replacement,proto3" json:"replacement,omitempty"`
	// If true, for given message there won't be generated
	// any transformers related to field paths or masks.
	// Should be used mostly for request/response objects.
	SkipFieldPathTransformers bool `protobuf:"varint,3,opt,name=skip_field_path_transformers,json=skipFieldPathTransformers,proto3" json:"skip_field_path_transformers,omitempty"`
	// Informs, whether goten should provide transformer
	// from old to new version only, from new to old version
	// only, or for both directions. For example, requests
	// need to be only "upgraded", responses need to be only
	// "downgraded", resources should be transformable in both
	// directions as they can be present in requests as responses.
	// By default, bi directional conversion is required.
	TransformationDirection ServiceObjectsVersioning_ObjectVersioning_TransformationDirection `protobuf:"varint,4,opt,name=transformation_direction,json=transformationDirection,proto3,enum=goten.annotations.ServiceObjectsVersioning_ObjectVersioning_TransformationDirection" json:"transformation_direction,omitempty"`
	// Applicable for resource messages only.
	// If set to true, goten will skip generation of
	// transformed resource access based on replacement resource
	SkipResourceAccessTransformer bool `protobuf:"varint,5,opt,name=skip_resource_access_transformer,json=skipResourceAccessTransformer,proto3" json:"skip_resource_access_transformer,omitempty"`
}

func (x *ServiceObjectsVersioning_ObjectVersioning) Reset() {
	*x = ServiceObjectsVersioning_ObjectVersioning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goten_annotations_versioning_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceObjectsVersioning_ObjectVersioning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceObjectsVersioning_ObjectVersioning) ProtoMessage() {}

func (x *ServiceObjectsVersioning_ObjectVersioning) ProtoReflect() protoreflect.Message {
	mi := &file_goten_annotations_versioning_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceObjectsVersioning_ObjectVersioning.ProtoReflect.Descriptor instead.
func (*ServiceObjectsVersioning_ObjectVersioning) Descriptor() ([]byte, []int) {
	return file_goten_annotations_versioning_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServiceObjectsVersioning_ObjectVersioning) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ServiceObjectsVersioning_ObjectVersioning) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

func (x *ServiceObjectsVersioning_ObjectVersioning) GetSkipFieldPathTransformers() bool {
	if x != nil {
		return x.SkipFieldPathTransformers
	}
	return false
}

func (x *ServiceObjectsVersioning_ObjectVersioning) GetTransformationDirection() ServiceObjectsVersioning_ObjectVersioning_TransformationDirection {
	if x != nil {
		return x.TransformationDirection
	}
	return ServiceObjectsVersioning_ObjectVersioning_BIDIRECTIONAL
}

func (x *ServiceObjectsVersioning_ObjectVersioning) GetSkipResourceAccessTransformer() bool {
	if x != nil {
		return x.SkipResourceAccessTransformer
	}
	return false
}

var file_goten_annotations_versioning_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*ServiceObjectsVersioning)(nil),
		Field:         69041,
		Name:          "goten.annotations.service_versioning",
		Tag:           "bytes,69041,opt,name=service_versioning",
		Filename:      "goten/annotations/versioning.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional goten.annotations.ServiceObjectsVersioning service_versioning = 69041;
	E_ServiceVersioning = &file_goten_annotations_versioning_proto_extTypes[0]
)

var File_goten_annotations_versioning_proto protoreflect.FileDescriptor

var file_goten_annotations_versioning_proto_rawDesc = []byte{
	0x0a, 0x22, 0x67, 0x6f, 0x74, 0x65, 0x6e, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x67, 0x6f, 0x74, 0x65, 0x6e, 0x2e, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x67, 0x6f, 0x74, 0x65, 0x6e,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x6f, 0x74,
	0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc, 0x05, 0x0a, 0x18, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x57, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x67, 0x6f, 0x74, 0x65, 0x6e, 0x2e, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x56,
	0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x3c, 0x2e, 0x67, 0x6f, 0x74, 0x65, 0x6e, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x1a, 0x5e, 0x0a, 0x11, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0xce, 0x03, 0x0a, 0x10, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x1c, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x19, 0x73, 0x6b, 0x69,
	0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x65, 0x72, 0x73, 0x12, 0x8f, 0x01, 0x0a, 0x18, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x54, 0x2e, 0x67, 0x6f, 0x74, 0x65,
	0x6e, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x17, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x20, 0x73, 0x6b, 0x69, 0x70,
	0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x1d, 0x73, 0x6b, 0x69, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65,
	0x72, 0x22, 0x64, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d,
	0x42, 0x49, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x54, 0x4f, 0x5f, 0x4f,
	0x4c, 0x44, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x4f, 0x4c, 0x44,
	0x5f, 0x54, 0x4f, 0x5f, 0x4e, 0x45, 0x57, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53,
	0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x3a, 0x7a, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb1, 0x9b, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x67, 0x6f, 0x74, 0x65, 0x6e, 0x2e, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67,
	0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x69, 0x6e, 0x67, 0x42, 0x70, 0x0a, 0x24, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x67,
	0x6f, 0x74, 0x65, 0x6e, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x42, 0x14, 0x47, 0x6f, 0x74,
	0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e,
	0x67, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77, 0x61, 0x6e, 0x2f, 0x67, 0x6f, 0x74, 0x65, 0x6e, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goten_annotations_versioning_proto_rawDescOnce sync.Once
	file_goten_annotations_versioning_proto_rawDescData = file_goten_annotations_versioning_proto_rawDesc
)

func file_goten_annotations_versioning_proto_rawDescGZIP() []byte {
	file_goten_annotations_versioning_proto_rawDescOnce.Do(func() {
		file_goten_annotations_versioning_proto_rawDescData = protoimpl.X.CompressGZIP(file_goten_annotations_versioning_proto_rawDescData)
	})
	return file_goten_annotations_versioning_proto_rawDescData
}

var file_goten_annotations_versioning_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goten_annotations_versioning_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_goten_annotations_versioning_proto_goTypes = []interface{}{
	(ServiceObjectsVersioning_ObjectVersioning_TransformationDirection)(0), // 0: goten.annotations.ServiceObjectsVersioning.ObjectVersioning.TransformationDirection
	(*ServiceObjectsVersioning)(nil),                                       // 1: goten.annotations.ServiceObjectsVersioning
	(*ServiceObjectsVersioning_MethodReplacement)(nil),                     // 2: goten.annotations.ServiceObjectsVersioning.MethodReplacement
	(*ServiceObjectsVersioning_ObjectVersioning)(nil),                      // 3: goten.annotations.ServiceObjectsVersioning.ObjectVersioning
	(*descriptorpb.FileOptions)(nil),                                       // 4: google.protobuf.FileOptions
}
var file_goten_annotations_versioning_proto_depIdxs = []int32{
	2, // 0: goten.annotations.ServiceObjectsVersioning.methods:type_name -> goten.annotations.ServiceObjectsVersioning.MethodReplacement
	3, // 1: goten.annotations.ServiceObjectsVersioning.objects:type_name -> goten.annotations.ServiceObjectsVersioning.ObjectVersioning
	0, // 2: goten.annotations.ServiceObjectsVersioning.ObjectVersioning.transformation_direction:type_name -> goten.annotations.ServiceObjectsVersioning.ObjectVersioning.TransformationDirection
	4, // 3: goten.annotations.service_versioning:extendee -> google.protobuf.FileOptions
	1, // 4: goten.annotations.service_versioning:type_name -> goten.annotations.ServiceObjectsVersioning
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	3, // [3:4] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_goten_annotations_versioning_proto_init() }
func file_goten_annotations_versioning_proto_init() {
	if File_goten_annotations_versioning_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goten_annotations_versioning_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceObjectsVersioning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goten_annotations_versioning_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceObjectsVersioning_MethodReplacement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goten_annotations_versioning_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceObjectsVersioning_ObjectVersioning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goten_annotations_versioning_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_goten_annotations_versioning_proto_goTypes,
		DependencyIndexes: file_goten_annotations_versioning_proto_depIdxs,
		EnumInfos:         file_goten_annotations_versioning_proto_enumTypes,
		MessageInfos:      file_goten_annotations_versioning_proto_msgTypes,
		ExtensionInfos:    file_goten_annotations_versioning_proto_extTypes,
	}.Build()
	File_goten_annotations_versioning_proto = out.File
	file_goten_annotations_versioning_proto_rawDesc = nil
	file_goten_annotations_versioning_proto_goTypes = nil
	file_goten_annotations_versioning_proto_depIdxs = nil
}
