// Code generated by protoc-gen-goten-object
// File: goten/meta-service/proto/v1/deployment.proto
// DO NOT EDIT!!!

package deployment

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/iancoleman/strcase"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoregistry"

	gotenobject "github.com/cloudwan/goten-sdk/runtime/object"
)

// proto imports
import (
	region "github.com/cloudwan/goten-sdk/meta-service/resources/v1/region"
	service "github.com/cloudwan/goten-sdk/meta-service/resources/v1/service"
	meta "github.com/cloudwan/goten-sdk/types/meta"
)

// ensure the imports are used
var (
	_ = new(json.Marshaler)
	_ = new(fmt.Stringer)
	_ = reflect.DeepEqual
	_ = strings.Builder{}
	_ = time.Second

	_ = strcase.ToLowerCamel
	_ = codes.NotFound
	_ = status.Status{}
	_ = protojson.UnmarshalOptions{}
	_ = new(proto.Message)
	_ = protoregistry.GlobalTypes

	_ = new(gotenobject.FieldPath)
)

// make sure we're using proto imports
var (
	_ = &region.Region{}
	_ = &service.Service{}
	_ = &meta.Meta{}
)

// FieldPath provides implementation to handle
// https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/field_mask.proto
type Deployment_FieldPath interface {
	gotenobject.FieldPath
	Selector() Deployment_FieldPathSelector
	Get(source *Deployment) []interface{}
	GetSingle(source *Deployment) (interface{}, bool)
	ClearValue(item *Deployment)

	// Those methods build corresponding Deployment_FieldPathValue
	// (or array of values) and holds passed value. Panics if injected type is incorrect.
	WithIValue(value interface{}) Deployment_FieldPathValue
	WithIArrayOfValues(values interface{}) Deployment_FieldPathArrayOfValues
	WithIArrayItemValue(value interface{}) Deployment_FieldPathArrayItemValue
}

type Deployment_FieldPathSelector int32

const (
	Deployment_FieldPathSelectorName                      Deployment_FieldPathSelector = 0
	Deployment_FieldPathSelectorMetadata                  Deployment_FieldPathSelector = 1
	Deployment_FieldPathSelectorServiceName               Deployment_FieldPathSelector = 2
	Deployment_FieldPathSelectorRegion                    Deployment_FieldPathSelector = 3
	Deployment_FieldPathSelectorPublicDomain              Deployment_FieldPathSelector = 4
	Deployment_FieldPathSelectorPrivateDomain             Deployment_FieldPathSelector = 5
	Deployment_FieldPathSelectorLocalNetworkId            Deployment_FieldPathSelector = 6
	Deployment_FieldPathSelectorLocation                  Deployment_FieldPathSelector = 7
	Deployment_FieldPathSelectorIsDisabled                Deployment_FieldPathSelector = 8
	Deployment_FieldPathSelectorEnvRegistryGeneration     Deployment_FieldPathSelector = 9
	Deployment_FieldPathSelectorCurrentVersion            Deployment_FieldPathSelector = 10
	Deployment_FieldPathSelectorAutomaticVersionSwitch    Deployment_FieldPathSelector = 11
	Deployment_FieldPathSelectorUpgradeState              Deployment_FieldPathSelector = 12
	Deployment_FieldPathSelectorAllowedServicesGeneration Deployment_FieldPathSelector = 13
)

func (s Deployment_FieldPathSelector) String() string {
	switch s {
	case Deployment_FieldPathSelectorName:
		return "name"
	case Deployment_FieldPathSelectorMetadata:
		return "metadata"
	case Deployment_FieldPathSelectorServiceName:
		return "service_name"
	case Deployment_FieldPathSelectorRegion:
		return "region"
	case Deployment_FieldPathSelectorPublicDomain:
		return "public_domain"
	case Deployment_FieldPathSelectorPrivateDomain:
		return "private_domain"
	case Deployment_FieldPathSelectorLocalNetworkId:
		return "local_network_id"
	case Deployment_FieldPathSelectorLocation:
		return "location"
	case Deployment_FieldPathSelectorIsDisabled:
		return "is_disabled"
	case Deployment_FieldPathSelectorEnvRegistryGeneration:
		return "env_registry_generation"
	case Deployment_FieldPathSelectorCurrentVersion:
		return "current_version"
	case Deployment_FieldPathSelectorAutomaticVersionSwitch:
		return "automatic_version_switch"
	case Deployment_FieldPathSelectorUpgradeState:
		return "upgrade_state"
	case Deployment_FieldPathSelectorAllowedServicesGeneration:
		return "allowed_services_generation"
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", s))
	}
}

func BuildDeployment_FieldPath(fp gotenobject.RawFieldPath) (Deployment_FieldPath, error) {
	if len(fp) == 0 {
		return nil, status.Error(codes.InvalidArgument, "empty field path for object Deployment")
	}
	if len(fp) == 1 {
		switch fp[0] {
		case "name":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorName}, nil
		case "metadata":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorMetadata}, nil
		case "service_name", "serviceName", "service-name":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorServiceName}, nil
		case "region":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorRegion}, nil
		case "public_domain", "publicDomain", "public-domain":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorPublicDomain}, nil
		case "private_domain", "privateDomain", "private-domain":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorPrivateDomain}, nil
		case "local_network_id", "localNetworkId", "local-network-id":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorLocalNetworkId}, nil
		case "location":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorLocation}, nil
		case "is_disabled", "isDisabled", "is-disabled":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorIsDisabled}, nil
		case "env_registry_generation", "envRegistryGeneration", "env-registry-generation":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorEnvRegistryGeneration}, nil
		case "current_version", "currentVersion", "current-version":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorCurrentVersion}, nil
		case "automatic_version_switch", "automaticVersionSwitch", "automatic-version-switch":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorAutomaticVersionSwitch}, nil
		case "upgrade_state", "upgradeState", "upgrade-state":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorUpgradeState}, nil
		case "allowed_services_generation", "allowedServicesGeneration", "allowed-services-generation":
			return &Deployment_FieldTerminalPath{selector: Deployment_FieldPathSelectorAllowedServicesGeneration}, nil
		}
	} else {
		switch fp[0] {
		case "metadata":
			if subpath, err := meta.BuildMeta_FieldPath(fp[1:]); err != nil {
				return nil, err
			} else {
				return &Deployment_FieldSubPath{selector: Deployment_FieldPathSelectorMetadata, subPath: subpath}, nil
			}
		case "location":
			if subpath, err := BuildDeploymentLocation_FieldPath(fp[1:]); err != nil {
				return nil, err
			} else {
				return &Deployment_FieldSubPath{selector: Deployment_FieldPathSelectorLocation, subPath: subpath}, nil
			}
		case "upgrade_state", "upgradeState", "upgrade-state":
			if subpath, err := BuildDeploymentUpgradeState_FieldPath(fp[1:]); err != nil {
				return nil, err
			} else {
				return &Deployment_FieldSubPath{selector: Deployment_FieldPathSelectorUpgradeState, subPath: subpath}, nil
			}
		}
	}
	return nil, status.Errorf(codes.InvalidArgument, "unknown field path '%s' for object Deployment", fp)
}

func ParseDeployment_FieldPath(rawField string) (Deployment_FieldPath, error) {
	fp, err := gotenobject.ParseRawFieldPath(rawField)
	if err != nil {
		return nil, err
	}
	return BuildDeployment_FieldPath(fp)
}

func MustParseDeployment_FieldPath(rawField string) Deployment_FieldPath {
	fp, err := ParseDeployment_FieldPath(rawField)
	if err != nil {
		panic(err)
	}
	return fp
}

type Deployment_FieldTerminalPath struct {
	selector Deployment_FieldPathSelector
}

var _ Deployment_FieldPath = (*Deployment_FieldTerminalPath)(nil)

func (fp *Deployment_FieldTerminalPath) Selector() Deployment_FieldPathSelector {
	return fp.selector
}

// String returns path representation in proto convention
func (fp *Deployment_FieldTerminalPath) String() string {
	return fp.selector.String()
}

// JSONString returns path representation is JSON convention
func (fp *Deployment_FieldTerminalPath) JSONString() string {
	return strcase.ToLowerCamel(fp.String())
}

// Get returns all values pointed by specific field from source Deployment
func (fp *Deployment_FieldTerminalPath) Get(source *Deployment) (values []interface{}) {
	if source != nil {
		switch fp.selector {
		case Deployment_FieldPathSelectorName:
			if source.Name != nil {
				values = append(values, source.Name)
			}
		case Deployment_FieldPathSelectorMetadata:
			if source.Metadata != nil {
				values = append(values, source.Metadata)
			}
		case Deployment_FieldPathSelectorServiceName:
			values = append(values, source.ServiceName)
		case Deployment_FieldPathSelectorRegion:
			if source.Region != nil {
				values = append(values, source.Region)
			}
		case Deployment_FieldPathSelectorPublicDomain:
			values = append(values, source.PublicDomain)
		case Deployment_FieldPathSelectorPrivateDomain:
			values = append(values, source.PrivateDomain)
		case Deployment_FieldPathSelectorLocalNetworkId:
			values = append(values, source.LocalNetworkId)
		case Deployment_FieldPathSelectorLocation:
			if source.Location != nil {
				values = append(values, source.Location)
			}
		case Deployment_FieldPathSelectorIsDisabled:
			values = append(values, source.IsDisabled)
		case Deployment_FieldPathSelectorEnvRegistryGeneration:
			values = append(values, source.EnvRegistryGeneration)
		case Deployment_FieldPathSelectorCurrentVersion:
			values = append(values, source.CurrentVersion)
		case Deployment_FieldPathSelectorAutomaticVersionSwitch:
			values = append(values, source.AutomaticVersionSwitch)
		case Deployment_FieldPathSelectorUpgradeState:
			if source.UpgradeState != nil {
				values = append(values, source.UpgradeState)
			}
		case Deployment_FieldPathSelectorAllowedServicesGeneration:
			values = append(values, source.AllowedServicesGeneration)
		default:
			panic(fmt.Sprintf("Invalid selector for Deployment: %d", fp.selector))
		}
	}
	return
}

func (fp *Deployment_FieldTerminalPath) GetRaw(source proto.Message) []interface{} {
	return fp.Get(source.(*Deployment))
}

// GetSingle returns value pointed by specific field of from source Deployment
func (fp *Deployment_FieldTerminalPath) GetSingle(source *Deployment) (interface{}, bool) {
	switch fp.selector {
	case Deployment_FieldPathSelectorName:
		res := source.GetName()
		return res, res != nil
	case Deployment_FieldPathSelectorMetadata:
		res := source.GetMetadata()
		return res, res != nil
	case Deployment_FieldPathSelectorServiceName:
		return source.GetServiceName(), source != nil
	case Deployment_FieldPathSelectorRegion:
		res := source.GetRegion()
		return res, res != nil
	case Deployment_FieldPathSelectorPublicDomain:
		return source.GetPublicDomain(), source != nil
	case Deployment_FieldPathSelectorPrivateDomain:
		return source.GetPrivateDomain(), source != nil
	case Deployment_FieldPathSelectorLocalNetworkId:
		return source.GetLocalNetworkId(), source != nil
	case Deployment_FieldPathSelectorLocation:
		res := source.GetLocation()
		return res, res != nil
	case Deployment_FieldPathSelectorIsDisabled:
		return source.GetIsDisabled(), source != nil
	case Deployment_FieldPathSelectorEnvRegistryGeneration:
		return source.GetEnvRegistryGeneration(), source != nil
	case Deployment_FieldPathSelectorCurrentVersion:
		return source.GetCurrentVersion(), source != nil
	case Deployment_FieldPathSelectorAutomaticVersionSwitch:
		return source.GetAutomaticVersionSwitch(), source != nil
	case Deployment_FieldPathSelectorUpgradeState:
		res := source.GetUpgradeState()
		return res, res != nil
	case Deployment_FieldPathSelectorAllowedServicesGeneration:
		return source.GetAllowedServicesGeneration(), source != nil
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fp.selector))
	}
}

func (fp *Deployment_FieldTerminalPath) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fp.GetSingle(source.(*Deployment))
}

// GetDefault returns a default value of the field type
func (fp *Deployment_FieldTerminalPath) GetDefault() interface{} {
	switch fp.selector {
	case Deployment_FieldPathSelectorName:
		return (*Name)(nil)
	case Deployment_FieldPathSelectorMetadata:
		return (*meta.Meta)(nil)
	case Deployment_FieldPathSelectorServiceName:
		return ""
	case Deployment_FieldPathSelectorRegion:
		return (*region.Reference)(nil)
	case Deployment_FieldPathSelectorPublicDomain:
		return ""
	case Deployment_FieldPathSelectorPrivateDomain:
		return ""
	case Deployment_FieldPathSelectorLocalNetworkId:
		return ""
	case Deployment_FieldPathSelectorLocation:
		return (*Deployment_Location)(nil)
	case Deployment_FieldPathSelectorIsDisabled:
		return false
	case Deployment_FieldPathSelectorEnvRegistryGeneration:
		return int32(0)
	case Deployment_FieldPathSelectorCurrentVersion:
		return ""
	case Deployment_FieldPathSelectorAutomaticVersionSwitch:
		return false
	case Deployment_FieldPathSelectorUpgradeState:
		return (*Deployment_UpgradeState)(nil)
	case Deployment_FieldPathSelectorAllowedServicesGeneration:
		return int64(0)
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fp.selector))
	}
}

func (fp *Deployment_FieldTerminalPath) ClearValue(item *Deployment) {
	if item != nil {
		switch fp.selector {
		case Deployment_FieldPathSelectorName:
			item.Name = nil
		case Deployment_FieldPathSelectorMetadata:
			item.Metadata = nil
		case Deployment_FieldPathSelectorServiceName:
			item.ServiceName = ""
		case Deployment_FieldPathSelectorRegion:
			item.Region = nil
		case Deployment_FieldPathSelectorPublicDomain:
			item.PublicDomain = ""
		case Deployment_FieldPathSelectorPrivateDomain:
			item.PrivateDomain = ""
		case Deployment_FieldPathSelectorLocalNetworkId:
			item.LocalNetworkId = ""
		case Deployment_FieldPathSelectorLocation:
			item.Location = nil
		case Deployment_FieldPathSelectorIsDisabled:
			item.IsDisabled = false
		case Deployment_FieldPathSelectorEnvRegistryGeneration:
			item.EnvRegistryGeneration = int32(0)
		case Deployment_FieldPathSelectorCurrentVersion:
			item.CurrentVersion = ""
		case Deployment_FieldPathSelectorAutomaticVersionSwitch:
			item.AutomaticVersionSwitch = false
		case Deployment_FieldPathSelectorUpgradeState:
			item.UpgradeState = nil
		case Deployment_FieldPathSelectorAllowedServicesGeneration:
			item.AllowedServicesGeneration = int64(0)
		default:
			panic(fmt.Sprintf("Invalid selector for Deployment: %d", fp.selector))
		}
	}
}

func (fp *Deployment_FieldTerminalPath) ClearValueRaw(item proto.Message) {
	fp.ClearValue(item.(*Deployment))
}

// IsLeaf - whether field path is holds simple value
func (fp *Deployment_FieldTerminalPath) IsLeaf() bool {
	return fp.selector == Deployment_FieldPathSelectorName ||
		fp.selector == Deployment_FieldPathSelectorServiceName ||
		fp.selector == Deployment_FieldPathSelectorRegion ||
		fp.selector == Deployment_FieldPathSelectorPublicDomain ||
		fp.selector == Deployment_FieldPathSelectorPrivateDomain ||
		fp.selector == Deployment_FieldPathSelectorLocalNetworkId ||
		fp.selector == Deployment_FieldPathSelectorIsDisabled ||
		fp.selector == Deployment_FieldPathSelectorEnvRegistryGeneration ||
		fp.selector == Deployment_FieldPathSelectorCurrentVersion ||
		fp.selector == Deployment_FieldPathSelectorAutomaticVersionSwitch ||
		fp.selector == Deployment_FieldPathSelectorAllowedServicesGeneration
}

func (fp *Deployment_FieldTerminalPath) SplitIntoTerminalIPaths() []gotenobject.FieldPath {
	return []gotenobject.FieldPath{fp}
}

func (fp *Deployment_FieldTerminalPath) WithIValue(value interface{}) Deployment_FieldPathValue {
	switch fp.selector {
	case Deployment_FieldPathSelectorName:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(*Name)}
	case Deployment_FieldPathSelectorMetadata:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(*meta.Meta)}
	case Deployment_FieldPathSelectorServiceName:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(string)}
	case Deployment_FieldPathSelectorRegion:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(*region.Reference)}
	case Deployment_FieldPathSelectorPublicDomain:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(string)}
	case Deployment_FieldPathSelectorPrivateDomain:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(string)}
	case Deployment_FieldPathSelectorLocalNetworkId:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(string)}
	case Deployment_FieldPathSelectorLocation:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(*Deployment_Location)}
	case Deployment_FieldPathSelectorIsDisabled:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(bool)}
	case Deployment_FieldPathSelectorEnvRegistryGeneration:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(int32)}
	case Deployment_FieldPathSelectorCurrentVersion:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(string)}
	case Deployment_FieldPathSelectorAutomaticVersionSwitch:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(bool)}
	case Deployment_FieldPathSelectorUpgradeState:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(*Deployment_UpgradeState)}
	case Deployment_FieldPathSelectorAllowedServicesGeneration:
		return &Deployment_FieldTerminalPathValue{Deployment_FieldTerminalPath: *fp, value: value.(int64)}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fp.selector))
	}
}

func (fp *Deployment_FieldTerminalPath) WithRawIValue(value interface{}) gotenobject.FieldPathValue {
	return fp.WithIValue(value)
}

func (fp *Deployment_FieldTerminalPath) WithIArrayOfValues(values interface{}) Deployment_FieldPathArrayOfValues {
	fpaov := &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp}
	switch fp.selector {
	case Deployment_FieldPathSelectorName:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]*Name)}
	case Deployment_FieldPathSelectorMetadata:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]*meta.Meta)}
	case Deployment_FieldPathSelectorServiceName:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]string)}
	case Deployment_FieldPathSelectorRegion:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]*region.Reference)}
	case Deployment_FieldPathSelectorPublicDomain:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]string)}
	case Deployment_FieldPathSelectorPrivateDomain:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]string)}
	case Deployment_FieldPathSelectorLocalNetworkId:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]string)}
	case Deployment_FieldPathSelectorLocation:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]*Deployment_Location)}
	case Deployment_FieldPathSelectorIsDisabled:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]bool)}
	case Deployment_FieldPathSelectorEnvRegistryGeneration:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]int32)}
	case Deployment_FieldPathSelectorCurrentVersion:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]string)}
	case Deployment_FieldPathSelectorAutomaticVersionSwitch:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]bool)}
	case Deployment_FieldPathSelectorUpgradeState:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]*Deployment_UpgradeState)}
	case Deployment_FieldPathSelectorAllowedServicesGeneration:
		return &Deployment_FieldTerminalPathArrayOfValues{Deployment_FieldTerminalPath: *fp, values: values.([]int64)}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fp.selector))
	}
	return fpaov
}

func (fp *Deployment_FieldTerminalPath) WithRawIArrayOfValues(values interface{}) gotenobject.FieldPathArrayOfValues {
	return fp.WithIArrayOfValues(values)
}

func (fp *Deployment_FieldTerminalPath) WithIArrayItemValue(value interface{}) Deployment_FieldPathArrayItemValue {
	switch fp.selector {
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fp.selector))
	}
}

func (fp *Deployment_FieldTerminalPath) WithRawIArrayItemValue(value interface{}) gotenobject.FieldPathArrayItemValue {
	return fp.WithIArrayItemValue(value)
}

type Deployment_FieldSubPath struct {
	selector Deployment_FieldPathSelector
	subPath  gotenobject.FieldPath
}

var _ Deployment_FieldPath = (*Deployment_FieldSubPath)(nil)

func (fps *Deployment_FieldSubPath) Selector() Deployment_FieldPathSelector {
	return fps.selector
}
func (fps *Deployment_FieldSubPath) AsMetadataSubPath() (meta.Meta_FieldPath, bool) {
	res, ok := fps.subPath.(meta.Meta_FieldPath)
	return res, ok
}
func (fps *Deployment_FieldSubPath) AsLocationSubPath() (DeploymentLocation_FieldPath, bool) {
	res, ok := fps.subPath.(DeploymentLocation_FieldPath)
	return res, ok
}
func (fps *Deployment_FieldSubPath) AsUpgradeStateSubPath() (DeploymentUpgradeState_FieldPath, bool) {
	res, ok := fps.subPath.(DeploymentUpgradeState_FieldPath)
	return res, ok
}

// String returns path representation in proto convention
func (fps *Deployment_FieldSubPath) String() string {
	return fps.selector.String() + "." + fps.subPath.String()
}

// JSONString returns path representation is JSON convention
func (fps *Deployment_FieldSubPath) JSONString() string {
	return strcase.ToLowerCamel(fps.selector.String()) + "." + fps.subPath.JSONString()
}

// Get returns all values pointed by selected field from source Deployment
func (fps *Deployment_FieldSubPath) Get(source *Deployment) (values []interface{}) {
	switch fps.selector {
	case Deployment_FieldPathSelectorMetadata:
		values = append(values, fps.subPath.GetRaw(source.GetMetadata())...)
	case Deployment_FieldPathSelectorLocation:
		values = append(values, fps.subPath.GetRaw(source.GetLocation())...)
	case Deployment_FieldPathSelectorUpgradeState:
		values = append(values, fps.subPath.GetRaw(source.GetUpgradeState())...)
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fps.selector))
	}
	return
}

func (fps *Deployment_FieldSubPath) GetRaw(source proto.Message) []interface{} {
	return fps.Get(source.(*Deployment))
}

// GetSingle returns value of selected field from source Deployment
func (fps *Deployment_FieldSubPath) GetSingle(source *Deployment) (interface{}, bool) {
	switch fps.selector {
	case Deployment_FieldPathSelectorMetadata:
		if source.GetMetadata() == nil {
			return nil, false
		}
		return fps.subPath.GetSingleRaw(source.GetMetadata())
	case Deployment_FieldPathSelectorLocation:
		if source.GetLocation() == nil {
			return nil, false
		}
		return fps.subPath.GetSingleRaw(source.GetLocation())
	case Deployment_FieldPathSelectorUpgradeState:
		if source.GetUpgradeState() == nil {
			return nil, false
		}
		return fps.subPath.GetSingleRaw(source.GetUpgradeState())
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fps.selector))
	}
}

func (fps *Deployment_FieldSubPath) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fps.GetSingle(source.(*Deployment))
}

// GetDefault returns a default value of the field type
func (fps *Deployment_FieldSubPath) GetDefault() interface{} {
	return fps.subPath.GetDefault()
}

func (fps *Deployment_FieldSubPath) ClearValue(item *Deployment) {
	if item != nil {
		switch fps.selector {
		case Deployment_FieldPathSelectorMetadata:
			fps.subPath.ClearValueRaw(item.Metadata)
		case Deployment_FieldPathSelectorLocation:
			fps.subPath.ClearValueRaw(item.Location)
		case Deployment_FieldPathSelectorUpgradeState:
			fps.subPath.ClearValueRaw(item.UpgradeState)
		default:
			panic(fmt.Sprintf("Invalid selector for Deployment: %d", fps.selector))
		}
	}
}

func (fps *Deployment_FieldSubPath) ClearValueRaw(item proto.Message) {
	fps.ClearValue(item.(*Deployment))
}

// IsLeaf - whether field path is holds simple value
func (fps *Deployment_FieldSubPath) IsLeaf() bool {
	return fps.subPath.IsLeaf()
}

func (fps *Deployment_FieldSubPath) SplitIntoTerminalIPaths() []gotenobject.FieldPath {
	iPaths := []gotenobject.FieldPath{&Deployment_FieldTerminalPath{selector: fps.selector}}
	iPaths = append(iPaths, fps.subPath.SplitIntoTerminalIPaths()...)
	return iPaths
}

func (fps *Deployment_FieldSubPath) WithIValue(value interface{}) Deployment_FieldPathValue {
	return &Deployment_FieldSubPathValue{fps, fps.subPath.WithRawIValue(value)}
}

func (fps *Deployment_FieldSubPath) WithRawIValue(value interface{}) gotenobject.FieldPathValue {
	return fps.WithIValue(value)
}

func (fps *Deployment_FieldSubPath) WithIArrayOfValues(values interface{}) Deployment_FieldPathArrayOfValues {
	return &Deployment_FieldSubPathArrayOfValues{fps, fps.subPath.WithRawIArrayOfValues(values)}
}

func (fps *Deployment_FieldSubPath) WithRawIArrayOfValues(values interface{}) gotenobject.FieldPathArrayOfValues {
	return fps.WithIArrayOfValues(values)
}

func (fps *Deployment_FieldSubPath) WithIArrayItemValue(value interface{}) Deployment_FieldPathArrayItemValue {
	return &Deployment_FieldSubPathArrayItemValue{fps, fps.subPath.WithRawIArrayItemValue(value)}
}

func (fps *Deployment_FieldSubPath) WithRawIArrayItemValue(value interface{}) gotenobject.FieldPathArrayItemValue {
	return fps.WithIArrayItemValue(value)
}

// Deployment_FieldPathValue allows storing values for Deployment fields according to their type
type Deployment_FieldPathValue interface {
	Deployment_FieldPath
	gotenobject.FieldPathValue
	SetTo(target **Deployment)
	CompareWith(*Deployment) (cmp int, comparable bool)
}

func ParseDeployment_FieldPathValue(pathStr, valueStr string) (Deployment_FieldPathValue, error) {
	fp, err := ParseDeployment_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpv, err := gotenobject.ParseFieldPathValue(fp, valueStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing Deployment field path value from %s: %v", valueStr, err)
	}
	return fpv.(Deployment_FieldPathValue), nil
}

func MustParseDeployment_FieldPathValue(pathStr, valueStr string) Deployment_FieldPathValue {
	fpv, err := ParseDeployment_FieldPathValue(pathStr, valueStr)
	if err != nil {
		panic(err)
	}
	return fpv
}

type Deployment_FieldTerminalPathValue struct {
	Deployment_FieldTerminalPath
	value interface{}
}

var _ Deployment_FieldPathValue = (*Deployment_FieldTerminalPathValue)(nil)

// GetRawValue returns raw value stored under selected path for 'Deployment' as interface{}
func (fpv *Deployment_FieldTerminalPathValue) GetRawValue() interface{} {
	return fpv.value
}
func (fpv *Deployment_FieldTerminalPathValue) AsNameValue() (*Name, bool) {
	res, ok := fpv.value.(*Name)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsMetadataValue() (*meta.Meta, bool) {
	res, ok := fpv.value.(*meta.Meta)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsServiceNameValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsRegionValue() (*region.Reference, bool) {
	res, ok := fpv.value.(*region.Reference)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsPublicDomainValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsPrivateDomainValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsLocalNetworkIdValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsLocationValue() (*Deployment_Location, bool) {
	res, ok := fpv.value.(*Deployment_Location)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsIsDisabledValue() (bool, bool) {
	res, ok := fpv.value.(bool)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsEnvRegistryGenerationValue() (int32, bool) {
	res, ok := fpv.value.(int32)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsCurrentVersionValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsAutomaticVersionSwitchValue() (bool, bool) {
	res, ok := fpv.value.(bool)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsUpgradeStateValue() (*Deployment_UpgradeState, bool) {
	res, ok := fpv.value.(*Deployment_UpgradeState)
	return res, ok
}
func (fpv *Deployment_FieldTerminalPathValue) AsAllowedServicesGenerationValue() (int64, bool) {
	res, ok := fpv.value.(int64)
	return res, ok
}

// SetTo stores value for selected field for object Deployment
func (fpv *Deployment_FieldTerminalPathValue) SetTo(target **Deployment) {
	if *target == nil {
		*target = new(Deployment)
	}
	switch fpv.selector {
	case Deployment_FieldPathSelectorName:
		(*target).Name = fpv.value.(*Name)
	case Deployment_FieldPathSelectorMetadata:
		(*target).Metadata = fpv.value.(*meta.Meta)
	case Deployment_FieldPathSelectorServiceName:
		(*target).ServiceName = fpv.value.(string)
	case Deployment_FieldPathSelectorRegion:
		(*target).Region = fpv.value.(*region.Reference)
	case Deployment_FieldPathSelectorPublicDomain:
		(*target).PublicDomain = fpv.value.(string)
	case Deployment_FieldPathSelectorPrivateDomain:
		(*target).PrivateDomain = fpv.value.(string)
	case Deployment_FieldPathSelectorLocalNetworkId:
		(*target).LocalNetworkId = fpv.value.(string)
	case Deployment_FieldPathSelectorLocation:
		(*target).Location = fpv.value.(*Deployment_Location)
	case Deployment_FieldPathSelectorIsDisabled:
		(*target).IsDisabled = fpv.value.(bool)
	case Deployment_FieldPathSelectorEnvRegistryGeneration:
		(*target).EnvRegistryGeneration = fpv.value.(int32)
	case Deployment_FieldPathSelectorCurrentVersion:
		(*target).CurrentVersion = fpv.value.(string)
	case Deployment_FieldPathSelectorAutomaticVersionSwitch:
		(*target).AutomaticVersionSwitch = fpv.value.(bool)
	case Deployment_FieldPathSelectorUpgradeState:
		(*target).UpgradeState = fpv.value.(*Deployment_UpgradeState)
	case Deployment_FieldPathSelectorAllowedServicesGeneration:
		(*target).AllowedServicesGeneration = fpv.value.(int64)
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fpv.selector))
	}
}

func (fpv *Deployment_FieldTerminalPathValue) SetToRaw(target proto.Message) {
	typedObject := target.(*Deployment)
	fpv.SetTo(&typedObject)
}

// CompareWith compares value in the 'Deployment_FieldTerminalPathValue' with the value under path in 'Deployment'.
func (fpv *Deployment_FieldTerminalPathValue) CompareWith(source *Deployment) (int, bool) {
	switch fpv.selector {
	case Deployment_FieldPathSelectorName:
		leftValue := fpv.value.(*Name)
		rightValue := source.GetName()
		if leftValue == nil {
			if rightValue != nil {
				return -1, true
			}
			return 0, true
		}
		if rightValue == nil {
			return 1, true
		}
		if leftValue.String() == rightValue.String() {
			return 0, true
		} else if leftValue.String() < rightValue.String() {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorMetadata:
		return 0, false
	case Deployment_FieldPathSelectorServiceName:
		leftValue := fpv.value.(string)
		rightValue := source.GetServiceName()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorRegion:
		leftValue := fpv.value.(*region.Reference)
		rightValue := source.GetRegion()
		if leftValue == nil {
			if rightValue != nil {
				return -1, true
			}
			return 0, true
		}
		if rightValue == nil {
			return 1, true
		}
		if leftValue.String() == rightValue.String() {
			return 0, true
		} else if leftValue.String() < rightValue.String() {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorPublicDomain:
		leftValue := fpv.value.(string)
		rightValue := source.GetPublicDomain()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorPrivateDomain:
		leftValue := fpv.value.(string)
		rightValue := source.GetPrivateDomain()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorLocalNetworkId:
		leftValue := fpv.value.(string)
		rightValue := source.GetLocalNetworkId()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorLocation:
		return 0, false
	case Deployment_FieldPathSelectorIsDisabled:
		leftValue := fpv.value.(bool)
		rightValue := source.GetIsDisabled()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if !(leftValue) && (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorEnvRegistryGeneration:
		leftValue := fpv.value.(int32)
		rightValue := source.GetEnvRegistryGeneration()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorCurrentVersion:
		leftValue := fpv.value.(string)
		rightValue := source.GetCurrentVersion()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorAutomaticVersionSwitch:
		leftValue := fpv.value.(bool)
		rightValue := source.GetAutomaticVersionSwitch()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if !(leftValue) && (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case Deployment_FieldPathSelectorUpgradeState:
		return 0, false
	case Deployment_FieldPathSelectorAllowedServicesGeneration:
		leftValue := fpv.value.(int64)
		rightValue := source.GetAllowedServicesGeneration()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fpv.selector))
	}
}

func (fpv *Deployment_FieldTerminalPathValue) CompareWithRaw(source proto.Message) (int, bool) {
	return fpv.CompareWith(source.(*Deployment))
}

type Deployment_FieldSubPathValue struct {
	Deployment_FieldPath
	subPathValue gotenobject.FieldPathValue
}

var _ Deployment_FieldPathValue = (*Deployment_FieldSubPathValue)(nil)

func (fpvs *Deployment_FieldSubPathValue) AsMetadataPathValue() (meta.Meta_FieldPathValue, bool) {
	res, ok := fpvs.subPathValue.(meta.Meta_FieldPathValue)
	return res, ok
}
func (fpvs *Deployment_FieldSubPathValue) AsLocationPathValue() (DeploymentLocation_FieldPathValue, bool) {
	res, ok := fpvs.subPathValue.(DeploymentLocation_FieldPathValue)
	return res, ok
}
func (fpvs *Deployment_FieldSubPathValue) AsUpgradeStatePathValue() (DeploymentUpgradeState_FieldPathValue, bool) {
	res, ok := fpvs.subPathValue.(DeploymentUpgradeState_FieldPathValue)
	return res, ok
}

func (fpvs *Deployment_FieldSubPathValue) SetTo(target **Deployment) {
	if *target == nil {
		*target = new(Deployment)
	}
	switch fpvs.Selector() {
	case Deployment_FieldPathSelectorMetadata:
		fpvs.subPathValue.(meta.Meta_FieldPathValue).SetTo(&(*target).Metadata)
	case Deployment_FieldPathSelectorLocation:
		fpvs.subPathValue.(DeploymentLocation_FieldPathValue).SetTo(&(*target).Location)
	case Deployment_FieldPathSelectorUpgradeState:
		fpvs.subPathValue.(DeploymentUpgradeState_FieldPathValue).SetTo(&(*target).UpgradeState)
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fpvs.Selector()))
	}
}

func (fpvs *Deployment_FieldSubPathValue) SetToRaw(target proto.Message) {
	typedObject := target.(*Deployment)
	fpvs.SetTo(&typedObject)
}

func (fpvs *Deployment_FieldSubPathValue) GetRawValue() interface{} {
	return fpvs.subPathValue.GetRawValue()
}

func (fpvs *Deployment_FieldSubPathValue) CompareWith(source *Deployment) (int, bool) {
	switch fpvs.Selector() {
	case Deployment_FieldPathSelectorMetadata:
		return fpvs.subPathValue.(meta.Meta_FieldPathValue).CompareWith(source.GetMetadata())
	case Deployment_FieldPathSelectorLocation:
		return fpvs.subPathValue.(DeploymentLocation_FieldPathValue).CompareWith(source.GetLocation())
	case Deployment_FieldPathSelectorUpgradeState:
		return fpvs.subPathValue.(DeploymentUpgradeState_FieldPathValue).CompareWith(source.GetUpgradeState())
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fpvs.Selector()))
	}
}

func (fpvs *Deployment_FieldSubPathValue) CompareWithRaw(source proto.Message) (int, bool) {
	return fpvs.CompareWith(source.(*Deployment))
}

// Deployment_FieldPathArrayItemValue allows storing single item in Path-specific values for Deployment according to their type
// Present only for array (repeated) types.
type Deployment_FieldPathArrayItemValue interface {
	gotenobject.FieldPathArrayItemValue
	Deployment_FieldPath
	ContainsValue(*Deployment) bool
}

// ParseDeployment_FieldPathArrayItemValue parses string and JSON-encoded value to its Value
func ParseDeployment_FieldPathArrayItemValue(pathStr, valueStr string) (Deployment_FieldPathArrayItemValue, error) {
	fp, err := ParseDeployment_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpaiv, err := gotenobject.ParseFieldPathArrayItemValue(fp, valueStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing Deployment field path array item value from %s: %v", valueStr, err)
	}
	return fpaiv.(Deployment_FieldPathArrayItemValue), nil
}

func MustParseDeployment_FieldPathArrayItemValue(pathStr, valueStr string) Deployment_FieldPathArrayItemValue {
	fpaiv, err := ParseDeployment_FieldPathArrayItemValue(pathStr, valueStr)
	if err != nil {
		panic(err)
	}
	return fpaiv
}

type Deployment_FieldTerminalPathArrayItemValue struct {
	Deployment_FieldTerminalPath
	value interface{}
}

var _ Deployment_FieldPathArrayItemValue = (*Deployment_FieldTerminalPathArrayItemValue)(nil)

// GetRawValue returns stored element value for array in object Deployment as interface{}
func (fpaiv *Deployment_FieldTerminalPathArrayItemValue) GetRawItemValue() interface{} {
	return fpaiv.value
}

func (fpaiv *Deployment_FieldTerminalPathArrayItemValue) GetSingle(source *Deployment) (interface{}, bool) {
	return nil, false
}

func (fpaiv *Deployment_FieldTerminalPathArrayItemValue) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fpaiv.GetSingle(source.(*Deployment))
}

// Contains returns a boolean indicating if value that is being held is present in given 'Deployment'
func (fpaiv *Deployment_FieldTerminalPathArrayItemValue) ContainsValue(source *Deployment) bool {
	slice := fpaiv.Deployment_FieldTerminalPath.Get(source)
	for _, v := range slice {
		if asProtoMsg, ok := fpaiv.value.(proto.Message); ok {
			if proto.Equal(asProtoMsg, v.(proto.Message)) {
				return true
			}
		} else if reflect.DeepEqual(v, fpaiv.value) {
			return true
		}
	}
	return false
}

type Deployment_FieldSubPathArrayItemValue struct {
	Deployment_FieldPath
	subPathItemValue gotenobject.FieldPathArrayItemValue
}

// GetRawValue returns stored array item value
func (fpaivs *Deployment_FieldSubPathArrayItemValue) GetRawItemValue() interface{} {
	return fpaivs.subPathItemValue.GetRawItemValue()
}
func (fpaivs *Deployment_FieldSubPathArrayItemValue) AsMetadataPathItemValue() (meta.Meta_FieldPathArrayItemValue, bool) {
	res, ok := fpaivs.subPathItemValue.(meta.Meta_FieldPathArrayItemValue)
	return res, ok
}
func (fpaivs *Deployment_FieldSubPathArrayItemValue) AsLocationPathItemValue() (DeploymentLocation_FieldPathArrayItemValue, bool) {
	res, ok := fpaivs.subPathItemValue.(DeploymentLocation_FieldPathArrayItemValue)
	return res, ok
}
func (fpaivs *Deployment_FieldSubPathArrayItemValue) AsUpgradeStatePathItemValue() (DeploymentUpgradeState_FieldPathArrayItemValue, bool) {
	res, ok := fpaivs.subPathItemValue.(DeploymentUpgradeState_FieldPathArrayItemValue)
	return res, ok
}

// Contains returns a boolean indicating if value that is being held is present in given 'Deployment'
func (fpaivs *Deployment_FieldSubPathArrayItemValue) ContainsValue(source *Deployment) bool {
	switch fpaivs.Selector() {
	case Deployment_FieldPathSelectorMetadata:
		return fpaivs.subPathItemValue.(meta.Meta_FieldPathArrayItemValue).ContainsValue(source.GetMetadata())
	case Deployment_FieldPathSelectorLocation:
		return fpaivs.subPathItemValue.(DeploymentLocation_FieldPathArrayItemValue).ContainsValue(source.GetLocation())
	case Deployment_FieldPathSelectorUpgradeState:
		return fpaivs.subPathItemValue.(DeploymentUpgradeState_FieldPathArrayItemValue).ContainsValue(source.GetUpgradeState())
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment: %d", fpaivs.Selector()))
	}
}

// Deployment_FieldPathArrayOfValues allows storing slice of values for Deployment fields according to their type
type Deployment_FieldPathArrayOfValues interface {
	gotenobject.FieldPathArrayOfValues
	Deployment_FieldPath
}

func ParseDeployment_FieldPathArrayOfValues(pathStr, valuesStr string) (Deployment_FieldPathArrayOfValues, error) {
	fp, err := ParseDeployment_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpaov, err := gotenobject.ParseFieldPathArrayOfValues(fp, valuesStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing Deployment field path array of values from %s: %v", valuesStr, err)
	}
	return fpaov.(Deployment_FieldPathArrayOfValues), nil
}

func MustParseDeployment_FieldPathArrayOfValues(pathStr, valuesStr string) Deployment_FieldPathArrayOfValues {
	fpaov, err := ParseDeployment_FieldPathArrayOfValues(pathStr, valuesStr)
	if err != nil {
		panic(err)
	}
	return fpaov
}

type Deployment_FieldTerminalPathArrayOfValues struct {
	Deployment_FieldTerminalPath
	values interface{}
}

var _ Deployment_FieldPathArrayOfValues = (*Deployment_FieldTerminalPathArrayOfValues)(nil)

func (fpaov *Deployment_FieldTerminalPathArrayOfValues) GetRawValues() (values []interface{}) {
	switch fpaov.selector {
	case Deployment_FieldPathSelectorName:
		for _, v := range fpaov.values.([]*Name) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorMetadata:
		for _, v := range fpaov.values.([]*meta.Meta) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorServiceName:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorRegion:
		for _, v := range fpaov.values.([]*region.Reference) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorPublicDomain:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorPrivateDomain:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorLocalNetworkId:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorLocation:
		for _, v := range fpaov.values.([]*Deployment_Location) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorIsDisabled:
		for _, v := range fpaov.values.([]bool) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorEnvRegistryGeneration:
		for _, v := range fpaov.values.([]int32) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorCurrentVersion:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorAutomaticVersionSwitch:
		for _, v := range fpaov.values.([]bool) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorUpgradeState:
		for _, v := range fpaov.values.([]*Deployment_UpgradeState) {
			values = append(values, v)
		}
	case Deployment_FieldPathSelectorAllowedServicesGeneration:
		for _, v := range fpaov.values.([]int64) {
			values = append(values, v)
		}
	}
	return
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsNameArrayOfValues() ([]*Name, bool) {
	res, ok := fpaov.values.([]*Name)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsMetadataArrayOfValues() ([]*meta.Meta, bool) {
	res, ok := fpaov.values.([]*meta.Meta)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsServiceNameArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsRegionArrayOfValues() ([]*region.Reference, bool) {
	res, ok := fpaov.values.([]*region.Reference)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsPublicDomainArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsPrivateDomainArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsLocalNetworkIdArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsLocationArrayOfValues() ([]*Deployment_Location, bool) {
	res, ok := fpaov.values.([]*Deployment_Location)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsIsDisabledArrayOfValues() ([]bool, bool) {
	res, ok := fpaov.values.([]bool)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsEnvRegistryGenerationArrayOfValues() ([]int32, bool) {
	res, ok := fpaov.values.([]int32)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsCurrentVersionArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsAutomaticVersionSwitchArrayOfValues() ([]bool, bool) {
	res, ok := fpaov.values.([]bool)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsUpgradeStateArrayOfValues() ([]*Deployment_UpgradeState, bool) {
	res, ok := fpaov.values.([]*Deployment_UpgradeState)
	return res, ok
}
func (fpaov *Deployment_FieldTerminalPathArrayOfValues) AsAllowedServicesGenerationArrayOfValues() ([]int64, bool) {
	res, ok := fpaov.values.([]int64)
	return res, ok
}

type Deployment_FieldSubPathArrayOfValues struct {
	Deployment_FieldPath
	subPathArrayOfValues gotenobject.FieldPathArrayOfValues
}

var _ Deployment_FieldPathArrayOfValues = (*Deployment_FieldSubPathArrayOfValues)(nil)

func (fpsaov *Deployment_FieldSubPathArrayOfValues) GetRawValues() []interface{} {
	return fpsaov.subPathArrayOfValues.GetRawValues()
}
func (fpsaov *Deployment_FieldSubPathArrayOfValues) AsMetadataPathArrayOfValues() (meta.Meta_FieldPathArrayOfValues, bool) {
	res, ok := fpsaov.subPathArrayOfValues.(meta.Meta_FieldPathArrayOfValues)
	return res, ok
}
func (fpsaov *Deployment_FieldSubPathArrayOfValues) AsLocationPathArrayOfValues() (DeploymentLocation_FieldPathArrayOfValues, bool) {
	res, ok := fpsaov.subPathArrayOfValues.(DeploymentLocation_FieldPathArrayOfValues)
	return res, ok
}
func (fpsaov *Deployment_FieldSubPathArrayOfValues) AsUpgradeStatePathArrayOfValues() (DeploymentUpgradeState_FieldPathArrayOfValues, bool) {
	res, ok := fpsaov.subPathArrayOfValues.(DeploymentUpgradeState_FieldPathArrayOfValues)
	return res, ok
}

// FieldPath provides implementation to handle
// https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/field_mask.proto
type DeploymentLocation_FieldPath interface {
	gotenobject.FieldPath
	Selector() DeploymentLocation_FieldPathSelector
	Get(source *Deployment_Location) []interface{}
	GetSingle(source *Deployment_Location) (interface{}, bool)
	ClearValue(item *Deployment_Location)

	// Those methods build corresponding DeploymentLocation_FieldPathValue
	// (or array of values) and holds passed value. Panics if injected type is incorrect.
	WithIValue(value interface{}) DeploymentLocation_FieldPathValue
	WithIArrayOfValues(values interface{}) DeploymentLocation_FieldPathArrayOfValues
	WithIArrayItemValue(value interface{}) DeploymentLocation_FieldPathArrayItemValue
}

type DeploymentLocation_FieldPathSelector int32

const (
	DeploymentLocation_FieldPathSelectorContinent     DeploymentLocation_FieldPathSelector = 0
	DeploymentLocation_FieldPathSelectorCountry       DeploymentLocation_FieldPathSelector = 1
	DeploymentLocation_FieldPathSelectorAgglomeration DeploymentLocation_FieldPathSelector = 2
	DeploymentLocation_FieldPathSelectorCity          DeploymentLocation_FieldPathSelector = 3
	DeploymentLocation_FieldPathSelectorCloud         DeploymentLocation_FieldPathSelector = 4
)

func (s DeploymentLocation_FieldPathSelector) String() string {
	switch s {
	case DeploymentLocation_FieldPathSelectorContinent:
		return "continent"
	case DeploymentLocation_FieldPathSelectorCountry:
		return "country"
	case DeploymentLocation_FieldPathSelectorAgglomeration:
		return "agglomeration"
	case DeploymentLocation_FieldPathSelectorCity:
		return "city"
	case DeploymentLocation_FieldPathSelectorCloud:
		return "cloud"
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", s))
	}
}

func BuildDeploymentLocation_FieldPath(fp gotenobject.RawFieldPath) (DeploymentLocation_FieldPath, error) {
	if len(fp) == 0 {
		return nil, status.Error(codes.InvalidArgument, "empty field path for object Deployment_Location")
	}
	if len(fp) == 1 {
		switch fp[0] {
		case "continent":
			return &DeploymentLocation_FieldTerminalPath{selector: DeploymentLocation_FieldPathSelectorContinent}, nil
		case "country":
			return &DeploymentLocation_FieldTerminalPath{selector: DeploymentLocation_FieldPathSelectorCountry}, nil
		case "agglomeration":
			return &DeploymentLocation_FieldTerminalPath{selector: DeploymentLocation_FieldPathSelectorAgglomeration}, nil
		case "city":
			return &DeploymentLocation_FieldTerminalPath{selector: DeploymentLocation_FieldPathSelectorCity}, nil
		case "cloud":
			return &DeploymentLocation_FieldTerminalPath{selector: DeploymentLocation_FieldPathSelectorCloud}, nil
		}
	}
	return nil, status.Errorf(codes.InvalidArgument, "unknown field path '%s' for object Deployment_Location", fp)
}

func ParseDeploymentLocation_FieldPath(rawField string) (DeploymentLocation_FieldPath, error) {
	fp, err := gotenobject.ParseRawFieldPath(rawField)
	if err != nil {
		return nil, err
	}
	return BuildDeploymentLocation_FieldPath(fp)
}

func MustParseDeploymentLocation_FieldPath(rawField string) DeploymentLocation_FieldPath {
	fp, err := ParseDeploymentLocation_FieldPath(rawField)
	if err != nil {
		panic(err)
	}
	return fp
}

type DeploymentLocation_FieldTerminalPath struct {
	selector DeploymentLocation_FieldPathSelector
}

var _ DeploymentLocation_FieldPath = (*DeploymentLocation_FieldTerminalPath)(nil)

func (fp *DeploymentLocation_FieldTerminalPath) Selector() DeploymentLocation_FieldPathSelector {
	return fp.selector
}

// String returns path representation in proto convention
func (fp *DeploymentLocation_FieldTerminalPath) String() string {
	return fp.selector.String()
}

// JSONString returns path representation is JSON convention
func (fp *DeploymentLocation_FieldTerminalPath) JSONString() string {
	return strcase.ToLowerCamel(fp.String())
}

// Get returns all values pointed by specific field from source Deployment_Location
func (fp *DeploymentLocation_FieldTerminalPath) Get(source *Deployment_Location) (values []interface{}) {
	if source != nil {
		switch fp.selector {
		case DeploymentLocation_FieldPathSelectorContinent:
			values = append(values, source.Continent)
		case DeploymentLocation_FieldPathSelectorCountry:
			values = append(values, source.Country)
		case DeploymentLocation_FieldPathSelectorAgglomeration:
			values = append(values, source.Agglomeration)
		case DeploymentLocation_FieldPathSelectorCity:
			values = append(values, source.City)
		case DeploymentLocation_FieldPathSelectorCloud:
			values = append(values, source.Cloud)
		default:
			panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fp.selector))
		}
	}
	return
}

func (fp *DeploymentLocation_FieldTerminalPath) GetRaw(source proto.Message) []interface{} {
	return fp.Get(source.(*Deployment_Location))
}

// GetSingle returns value pointed by specific field of from source Deployment_Location
func (fp *DeploymentLocation_FieldTerminalPath) GetSingle(source *Deployment_Location) (interface{}, bool) {
	switch fp.selector {
	case DeploymentLocation_FieldPathSelectorContinent:
		return source.GetContinent(), source != nil
	case DeploymentLocation_FieldPathSelectorCountry:
		return source.GetCountry(), source != nil
	case DeploymentLocation_FieldPathSelectorAgglomeration:
		return source.GetAgglomeration(), source != nil
	case DeploymentLocation_FieldPathSelectorCity:
		return source.GetCity(), source != nil
	case DeploymentLocation_FieldPathSelectorCloud:
		return source.GetCloud(), source != nil
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fp.selector))
	}
}

func (fp *DeploymentLocation_FieldTerminalPath) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fp.GetSingle(source.(*Deployment_Location))
}

// GetDefault returns a default value of the field type
func (fp *DeploymentLocation_FieldTerminalPath) GetDefault() interface{} {
	switch fp.selector {
	case DeploymentLocation_FieldPathSelectorContinent:
		return ""
	case DeploymentLocation_FieldPathSelectorCountry:
		return ""
	case DeploymentLocation_FieldPathSelectorAgglomeration:
		return ""
	case DeploymentLocation_FieldPathSelectorCity:
		return ""
	case DeploymentLocation_FieldPathSelectorCloud:
		return ""
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fp.selector))
	}
}

func (fp *DeploymentLocation_FieldTerminalPath) ClearValue(item *Deployment_Location) {
	if item != nil {
		switch fp.selector {
		case DeploymentLocation_FieldPathSelectorContinent:
			item.Continent = ""
		case DeploymentLocation_FieldPathSelectorCountry:
			item.Country = ""
		case DeploymentLocation_FieldPathSelectorAgglomeration:
			item.Agglomeration = ""
		case DeploymentLocation_FieldPathSelectorCity:
			item.City = ""
		case DeploymentLocation_FieldPathSelectorCloud:
			item.Cloud = ""
		default:
			panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fp.selector))
		}
	}
}

func (fp *DeploymentLocation_FieldTerminalPath) ClearValueRaw(item proto.Message) {
	fp.ClearValue(item.(*Deployment_Location))
}

// IsLeaf - whether field path is holds simple value
func (fp *DeploymentLocation_FieldTerminalPath) IsLeaf() bool {
	return fp.selector == DeploymentLocation_FieldPathSelectorContinent ||
		fp.selector == DeploymentLocation_FieldPathSelectorCountry ||
		fp.selector == DeploymentLocation_FieldPathSelectorAgglomeration ||
		fp.selector == DeploymentLocation_FieldPathSelectorCity ||
		fp.selector == DeploymentLocation_FieldPathSelectorCloud
}

func (fp *DeploymentLocation_FieldTerminalPath) SplitIntoTerminalIPaths() []gotenobject.FieldPath {
	return []gotenobject.FieldPath{fp}
}

func (fp *DeploymentLocation_FieldTerminalPath) WithIValue(value interface{}) DeploymentLocation_FieldPathValue {
	switch fp.selector {
	case DeploymentLocation_FieldPathSelectorContinent:
		return &DeploymentLocation_FieldTerminalPathValue{DeploymentLocation_FieldTerminalPath: *fp, value: value.(string)}
	case DeploymentLocation_FieldPathSelectorCountry:
		return &DeploymentLocation_FieldTerminalPathValue{DeploymentLocation_FieldTerminalPath: *fp, value: value.(string)}
	case DeploymentLocation_FieldPathSelectorAgglomeration:
		return &DeploymentLocation_FieldTerminalPathValue{DeploymentLocation_FieldTerminalPath: *fp, value: value.(string)}
	case DeploymentLocation_FieldPathSelectorCity:
		return &DeploymentLocation_FieldTerminalPathValue{DeploymentLocation_FieldTerminalPath: *fp, value: value.(string)}
	case DeploymentLocation_FieldPathSelectorCloud:
		return &DeploymentLocation_FieldTerminalPathValue{DeploymentLocation_FieldTerminalPath: *fp, value: value.(string)}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fp.selector))
	}
}

func (fp *DeploymentLocation_FieldTerminalPath) WithRawIValue(value interface{}) gotenobject.FieldPathValue {
	return fp.WithIValue(value)
}

func (fp *DeploymentLocation_FieldTerminalPath) WithIArrayOfValues(values interface{}) DeploymentLocation_FieldPathArrayOfValues {
	fpaov := &DeploymentLocation_FieldTerminalPathArrayOfValues{DeploymentLocation_FieldTerminalPath: *fp}
	switch fp.selector {
	case DeploymentLocation_FieldPathSelectorContinent:
		return &DeploymentLocation_FieldTerminalPathArrayOfValues{DeploymentLocation_FieldTerminalPath: *fp, values: values.([]string)}
	case DeploymentLocation_FieldPathSelectorCountry:
		return &DeploymentLocation_FieldTerminalPathArrayOfValues{DeploymentLocation_FieldTerminalPath: *fp, values: values.([]string)}
	case DeploymentLocation_FieldPathSelectorAgglomeration:
		return &DeploymentLocation_FieldTerminalPathArrayOfValues{DeploymentLocation_FieldTerminalPath: *fp, values: values.([]string)}
	case DeploymentLocation_FieldPathSelectorCity:
		return &DeploymentLocation_FieldTerminalPathArrayOfValues{DeploymentLocation_FieldTerminalPath: *fp, values: values.([]string)}
	case DeploymentLocation_FieldPathSelectorCloud:
		return &DeploymentLocation_FieldTerminalPathArrayOfValues{DeploymentLocation_FieldTerminalPath: *fp, values: values.([]string)}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fp.selector))
	}
	return fpaov
}

func (fp *DeploymentLocation_FieldTerminalPath) WithRawIArrayOfValues(values interface{}) gotenobject.FieldPathArrayOfValues {
	return fp.WithIArrayOfValues(values)
}

func (fp *DeploymentLocation_FieldTerminalPath) WithIArrayItemValue(value interface{}) DeploymentLocation_FieldPathArrayItemValue {
	switch fp.selector {
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fp.selector))
	}
}

func (fp *DeploymentLocation_FieldTerminalPath) WithRawIArrayItemValue(value interface{}) gotenobject.FieldPathArrayItemValue {
	return fp.WithIArrayItemValue(value)
}

// DeploymentLocation_FieldPathValue allows storing values for Location fields according to their type
type DeploymentLocation_FieldPathValue interface {
	DeploymentLocation_FieldPath
	gotenobject.FieldPathValue
	SetTo(target **Deployment_Location)
	CompareWith(*Deployment_Location) (cmp int, comparable bool)
}

func ParseDeploymentLocation_FieldPathValue(pathStr, valueStr string) (DeploymentLocation_FieldPathValue, error) {
	fp, err := ParseDeploymentLocation_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpv, err := gotenobject.ParseFieldPathValue(fp, valueStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing Location field path value from %s: %v", valueStr, err)
	}
	return fpv.(DeploymentLocation_FieldPathValue), nil
}

func MustParseDeploymentLocation_FieldPathValue(pathStr, valueStr string) DeploymentLocation_FieldPathValue {
	fpv, err := ParseDeploymentLocation_FieldPathValue(pathStr, valueStr)
	if err != nil {
		panic(err)
	}
	return fpv
}

type DeploymentLocation_FieldTerminalPathValue struct {
	DeploymentLocation_FieldTerminalPath
	value interface{}
}

var _ DeploymentLocation_FieldPathValue = (*DeploymentLocation_FieldTerminalPathValue)(nil)

// GetRawValue returns raw value stored under selected path for 'Location' as interface{}
func (fpv *DeploymentLocation_FieldTerminalPathValue) GetRawValue() interface{} {
	return fpv.value
}
func (fpv *DeploymentLocation_FieldTerminalPathValue) AsContinentValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *DeploymentLocation_FieldTerminalPathValue) AsCountryValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *DeploymentLocation_FieldTerminalPathValue) AsAgglomerationValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *DeploymentLocation_FieldTerminalPathValue) AsCityValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *DeploymentLocation_FieldTerminalPathValue) AsCloudValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}

// SetTo stores value for selected field for object Location
func (fpv *DeploymentLocation_FieldTerminalPathValue) SetTo(target **Deployment_Location) {
	if *target == nil {
		*target = new(Deployment_Location)
	}
	switch fpv.selector {
	case DeploymentLocation_FieldPathSelectorContinent:
		(*target).Continent = fpv.value.(string)
	case DeploymentLocation_FieldPathSelectorCountry:
		(*target).Country = fpv.value.(string)
	case DeploymentLocation_FieldPathSelectorAgglomeration:
		(*target).Agglomeration = fpv.value.(string)
	case DeploymentLocation_FieldPathSelectorCity:
		(*target).City = fpv.value.(string)
	case DeploymentLocation_FieldPathSelectorCloud:
		(*target).Cloud = fpv.value.(string)
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fpv.selector))
	}
}

func (fpv *DeploymentLocation_FieldTerminalPathValue) SetToRaw(target proto.Message) {
	typedObject := target.(*Deployment_Location)
	fpv.SetTo(&typedObject)
}

// CompareWith compares value in the 'DeploymentLocation_FieldTerminalPathValue' with the value under path in 'Deployment_Location'.
func (fpv *DeploymentLocation_FieldTerminalPathValue) CompareWith(source *Deployment_Location) (int, bool) {
	switch fpv.selector {
	case DeploymentLocation_FieldPathSelectorContinent:
		leftValue := fpv.value.(string)
		rightValue := source.GetContinent()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case DeploymentLocation_FieldPathSelectorCountry:
		leftValue := fpv.value.(string)
		rightValue := source.GetCountry()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case DeploymentLocation_FieldPathSelectorAgglomeration:
		leftValue := fpv.value.(string)
		rightValue := source.GetAgglomeration()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case DeploymentLocation_FieldPathSelectorCity:
		leftValue := fpv.value.(string)
		rightValue := source.GetCity()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case DeploymentLocation_FieldPathSelectorCloud:
		leftValue := fpv.value.(string)
		rightValue := source.GetCloud()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_Location: %d", fpv.selector))
	}
}

func (fpv *DeploymentLocation_FieldTerminalPathValue) CompareWithRaw(source proto.Message) (int, bool) {
	return fpv.CompareWith(source.(*Deployment_Location))
}

// DeploymentLocation_FieldPathArrayItemValue allows storing single item in Path-specific values for Location according to their type
// Present only for array (repeated) types.
type DeploymentLocation_FieldPathArrayItemValue interface {
	gotenobject.FieldPathArrayItemValue
	DeploymentLocation_FieldPath
	ContainsValue(*Deployment_Location) bool
}

// ParseDeploymentLocation_FieldPathArrayItemValue parses string and JSON-encoded value to its Value
func ParseDeploymentLocation_FieldPathArrayItemValue(pathStr, valueStr string) (DeploymentLocation_FieldPathArrayItemValue, error) {
	fp, err := ParseDeploymentLocation_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpaiv, err := gotenobject.ParseFieldPathArrayItemValue(fp, valueStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing Location field path array item value from %s: %v", valueStr, err)
	}
	return fpaiv.(DeploymentLocation_FieldPathArrayItemValue), nil
}

func MustParseDeploymentLocation_FieldPathArrayItemValue(pathStr, valueStr string) DeploymentLocation_FieldPathArrayItemValue {
	fpaiv, err := ParseDeploymentLocation_FieldPathArrayItemValue(pathStr, valueStr)
	if err != nil {
		panic(err)
	}
	return fpaiv
}

type DeploymentLocation_FieldTerminalPathArrayItemValue struct {
	DeploymentLocation_FieldTerminalPath
	value interface{}
}

var _ DeploymentLocation_FieldPathArrayItemValue = (*DeploymentLocation_FieldTerminalPathArrayItemValue)(nil)

// GetRawValue returns stored element value for array in object Deployment_Location as interface{}
func (fpaiv *DeploymentLocation_FieldTerminalPathArrayItemValue) GetRawItemValue() interface{} {
	return fpaiv.value
}

func (fpaiv *DeploymentLocation_FieldTerminalPathArrayItemValue) GetSingle(source *Deployment_Location) (interface{}, bool) {
	return nil, false
}

func (fpaiv *DeploymentLocation_FieldTerminalPathArrayItemValue) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fpaiv.GetSingle(source.(*Deployment_Location))
}

// Contains returns a boolean indicating if value that is being held is present in given 'Location'
func (fpaiv *DeploymentLocation_FieldTerminalPathArrayItemValue) ContainsValue(source *Deployment_Location) bool {
	slice := fpaiv.DeploymentLocation_FieldTerminalPath.Get(source)
	for _, v := range slice {
		if asProtoMsg, ok := fpaiv.value.(proto.Message); ok {
			if proto.Equal(asProtoMsg, v.(proto.Message)) {
				return true
			}
		} else if reflect.DeepEqual(v, fpaiv.value) {
			return true
		}
	}
	return false
}

// DeploymentLocation_FieldPathArrayOfValues allows storing slice of values for Location fields according to their type
type DeploymentLocation_FieldPathArrayOfValues interface {
	gotenobject.FieldPathArrayOfValues
	DeploymentLocation_FieldPath
}

func ParseDeploymentLocation_FieldPathArrayOfValues(pathStr, valuesStr string) (DeploymentLocation_FieldPathArrayOfValues, error) {
	fp, err := ParseDeploymentLocation_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpaov, err := gotenobject.ParseFieldPathArrayOfValues(fp, valuesStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing Location field path array of values from %s: %v", valuesStr, err)
	}
	return fpaov.(DeploymentLocation_FieldPathArrayOfValues), nil
}

func MustParseDeploymentLocation_FieldPathArrayOfValues(pathStr, valuesStr string) DeploymentLocation_FieldPathArrayOfValues {
	fpaov, err := ParseDeploymentLocation_FieldPathArrayOfValues(pathStr, valuesStr)
	if err != nil {
		panic(err)
	}
	return fpaov
}

type DeploymentLocation_FieldTerminalPathArrayOfValues struct {
	DeploymentLocation_FieldTerminalPath
	values interface{}
}

var _ DeploymentLocation_FieldPathArrayOfValues = (*DeploymentLocation_FieldTerminalPathArrayOfValues)(nil)

func (fpaov *DeploymentLocation_FieldTerminalPathArrayOfValues) GetRawValues() (values []interface{}) {
	switch fpaov.selector {
	case DeploymentLocation_FieldPathSelectorContinent:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case DeploymentLocation_FieldPathSelectorCountry:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case DeploymentLocation_FieldPathSelectorAgglomeration:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case DeploymentLocation_FieldPathSelectorCity:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case DeploymentLocation_FieldPathSelectorCloud:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	}
	return
}
func (fpaov *DeploymentLocation_FieldTerminalPathArrayOfValues) AsContinentArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *DeploymentLocation_FieldTerminalPathArrayOfValues) AsCountryArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *DeploymentLocation_FieldTerminalPathArrayOfValues) AsAgglomerationArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *DeploymentLocation_FieldTerminalPathArrayOfValues) AsCityArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *DeploymentLocation_FieldTerminalPathArrayOfValues) AsCloudArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}

// FieldPath provides implementation to handle
// https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/field_mask.proto
type DeploymentUpgradeState_FieldPath interface {
	gotenobject.FieldPath
	Selector() DeploymentUpgradeState_FieldPathSelector
	Get(source *Deployment_UpgradeState) []interface{}
	GetSingle(source *Deployment_UpgradeState) (interface{}, bool)
	ClearValue(item *Deployment_UpgradeState)

	// Those methods build corresponding DeploymentUpgradeState_FieldPathValue
	// (or array of values) and holds passed value. Panics if injected type is incorrect.
	WithIValue(value interface{}) DeploymentUpgradeState_FieldPathValue
	WithIArrayOfValues(values interface{}) DeploymentUpgradeState_FieldPathArrayOfValues
	WithIArrayItemValue(value interface{}) DeploymentUpgradeState_FieldPathArrayItemValue
}

type DeploymentUpgradeState_FieldPathSelector int32

const (
	DeploymentUpgradeState_FieldPathSelectorTargetVersion DeploymentUpgradeState_FieldPathSelector = 0
	DeploymentUpgradeState_FieldPathSelectorReadyShards   DeploymentUpgradeState_FieldPathSelector = 1
	DeploymentUpgradeState_FieldPathSelectorPendingShards DeploymentUpgradeState_FieldPathSelector = 2
	DeploymentUpgradeState_FieldPathSelectorStage         DeploymentUpgradeState_FieldPathSelector = 3
)

func (s DeploymentUpgradeState_FieldPathSelector) String() string {
	switch s {
	case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
		return "target_version"
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		return "ready_shards"
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		return "pending_shards"
	case DeploymentUpgradeState_FieldPathSelectorStage:
		return "stage"
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", s))
	}
}

func BuildDeploymentUpgradeState_FieldPath(fp gotenobject.RawFieldPath) (DeploymentUpgradeState_FieldPath, error) {
	if len(fp) == 0 {
		return nil, status.Error(codes.InvalidArgument, "empty field path for object Deployment_UpgradeState")
	}
	if len(fp) == 1 {
		switch fp[0] {
		case "target_version", "targetVersion", "target-version":
			return &DeploymentUpgradeState_FieldTerminalPath{selector: DeploymentUpgradeState_FieldPathSelectorTargetVersion}, nil
		case "ready_shards", "readyShards", "ready-shards":
			return &DeploymentUpgradeState_FieldTerminalPath{selector: DeploymentUpgradeState_FieldPathSelectorReadyShards}, nil
		case "pending_shards", "pendingShards", "pending-shards":
			return &DeploymentUpgradeState_FieldTerminalPath{selector: DeploymentUpgradeState_FieldPathSelectorPendingShards}, nil
		case "stage":
			return &DeploymentUpgradeState_FieldTerminalPath{selector: DeploymentUpgradeState_FieldPathSelectorStage}, nil
		}
	}
	return nil, status.Errorf(codes.InvalidArgument, "unknown field path '%s' for object Deployment_UpgradeState", fp)
}

func ParseDeploymentUpgradeState_FieldPath(rawField string) (DeploymentUpgradeState_FieldPath, error) {
	fp, err := gotenobject.ParseRawFieldPath(rawField)
	if err != nil {
		return nil, err
	}
	return BuildDeploymentUpgradeState_FieldPath(fp)
}

func MustParseDeploymentUpgradeState_FieldPath(rawField string) DeploymentUpgradeState_FieldPath {
	fp, err := ParseDeploymentUpgradeState_FieldPath(rawField)
	if err != nil {
		panic(err)
	}
	return fp
}

type DeploymentUpgradeState_FieldTerminalPath struct {
	selector DeploymentUpgradeState_FieldPathSelector
}

var _ DeploymentUpgradeState_FieldPath = (*DeploymentUpgradeState_FieldTerminalPath)(nil)

func (fp *DeploymentUpgradeState_FieldTerminalPath) Selector() DeploymentUpgradeState_FieldPathSelector {
	return fp.selector
}

// String returns path representation in proto convention
func (fp *DeploymentUpgradeState_FieldTerminalPath) String() string {
	return fp.selector.String()
}

// JSONString returns path representation is JSON convention
func (fp *DeploymentUpgradeState_FieldTerminalPath) JSONString() string {
	return strcase.ToLowerCamel(fp.String())
}

// Get returns all values pointed by specific field from source Deployment_UpgradeState
func (fp *DeploymentUpgradeState_FieldTerminalPath) Get(source *Deployment_UpgradeState) (values []interface{}) {
	if source != nil {
		switch fp.selector {
		case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
			values = append(values, source.TargetVersion)
		case DeploymentUpgradeState_FieldPathSelectorReadyShards:
			for _, value := range source.GetReadyShards() {
				values = append(values, value)
			}
		case DeploymentUpgradeState_FieldPathSelectorPendingShards:
			for _, value := range source.GetPendingShards() {
				values = append(values, value)
			}
		case DeploymentUpgradeState_FieldPathSelectorStage:
			values = append(values, source.Stage)
		default:
			panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fp.selector))
		}
	}
	return
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) GetRaw(source proto.Message) []interface{} {
	return fp.Get(source.(*Deployment_UpgradeState))
}

// GetSingle returns value pointed by specific field of from source Deployment_UpgradeState
func (fp *DeploymentUpgradeState_FieldTerminalPath) GetSingle(source *Deployment_UpgradeState) (interface{}, bool) {
	switch fp.selector {
	case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
		return source.GetTargetVersion(), source != nil
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		res := source.GetReadyShards()
		return res, res != nil
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		res := source.GetPendingShards()
		return res, res != nil
	case DeploymentUpgradeState_FieldPathSelectorStage:
		return source.GetStage(), source != nil
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fp.selector))
	}
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fp.GetSingle(source.(*Deployment_UpgradeState))
}

// GetDefault returns a default value of the field type
func (fp *DeploymentUpgradeState_FieldTerminalPath) GetDefault() interface{} {
	switch fp.selector {
	case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
		return ""
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		return ([]int64)(nil)
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		return ([]int64)(nil)
	case DeploymentUpgradeState_FieldPathSelectorStage:
		return Deployment_UpgradeState_READY
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fp.selector))
	}
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) ClearValue(item *Deployment_UpgradeState) {
	if item != nil {
		switch fp.selector {
		case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
			item.TargetVersion = ""
		case DeploymentUpgradeState_FieldPathSelectorReadyShards:
			item.ReadyShards = nil
		case DeploymentUpgradeState_FieldPathSelectorPendingShards:
			item.PendingShards = nil
		case DeploymentUpgradeState_FieldPathSelectorStage:
			item.Stage = Deployment_UpgradeState_READY
		default:
			panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fp.selector))
		}
	}
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) ClearValueRaw(item proto.Message) {
	fp.ClearValue(item.(*Deployment_UpgradeState))
}

// IsLeaf - whether field path is holds simple value
func (fp *DeploymentUpgradeState_FieldTerminalPath) IsLeaf() bool {
	return fp.selector == DeploymentUpgradeState_FieldPathSelectorTargetVersion ||
		fp.selector == DeploymentUpgradeState_FieldPathSelectorReadyShards ||
		fp.selector == DeploymentUpgradeState_FieldPathSelectorPendingShards ||
		fp.selector == DeploymentUpgradeState_FieldPathSelectorStage
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) SplitIntoTerminalIPaths() []gotenobject.FieldPath {
	return []gotenobject.FieldPath{fp}
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) WithIValue(value interface{}) DeploymentUpgradeState_FieldPathValue {
	switch fp.selector {
	case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
		return &DeploymentUpgradeState_FieldTerminalPathValue{DeploymentUpgradeState_FieldTerminalPath: *fp, value: value.(string)}
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		return &DeploymentUpgradeState_FieldTerminalPathValue{DeploymentUpgradeState_FieldTerminalPath: *fp, value: value.([]int64)}
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		return &DeploymentUpgradeState_FieldTerminalPathValue{DeploymentUpgradeState_FieldTerminalPath: *fp, value: value.([]int64)}
	case DeploymentUpgradeState_FieldPathSelectorStage:
		return &DeploymentUpgradeState_FieldTerminalPathValue{DeploymentUpgradeState_FieldTerminalPath: *fp, value: value.(Deployment_UpgradeState_Stage)}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fp.selector))
	}
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) WithRawIValue(value interface{}) gotenobject.FieldPathValue {
	return fp.WithIValue(value)
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) WithIArrayOfValues(values interface{}) DeploymentUpgradeState_FieldPathArrayOfValues {
	fpaov := &DeploymentUpgradeState_FieldTerminalPathArrayOfValues{DeploymentUpgradeState_FieldTerminalPath: *fp}
	switch fp.selector {
	case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
		return &DeploymentUpgradeState_FieldTerminalPathArrayOfValues{DeploymentUpgradeState_FieldTerminalPath: *fp, values: values.([]string)}
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		return &DeploymentUpgradeState_FieldTerminalPathArrayOfValues{DeploymentUpgradeState_FieldTerminalPath: *fp, values: values.([][]int64)}
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		return &DeploymentUpgradeState_FieldTerminalPathArrayOfValues{DeploymentUpgradeState_FieldTerminalPath: *fp, values: values.([][]int64)}
	case DeploymentUpgradeState_FieldPathSelectorStage:
		return &DeploymentUpgradeState_FieldTerminalPathArrayOfValues{DeploymentUpgradeState_FieldTerminalPath: *fp, values: values.([]Deployment_UpgradeState_Stage)}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fp.selector))
	}
	return fpaov
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) WithRawIArrayOfValues(values interface{}) gotenobject.FieldPathArrayOfValues {
	return fp.WithIArrayOfValues(values)
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) WithIArrayItemValue(value interface{}) DeploymentUpgradeState_FieldPathArrayItemValue {
	switch fp.selector {
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		return &DeploymentUpgradeState_FieldTerminalPathArrayItemValue{DeploymentUpgradeState_FieldTerminalPath: *fp, value: value.(int64)}
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		return &DeploymentUpgradeState_FieldTerminalPathArrayItemValue{DeploymentUpgradeState_FieldTerminalPath: *fp, value: value.(int64)}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fp.selector))
	}
}

func (fp *DeploymentUpgradeState_FieldTerminalPath) WithRawIArrayItemValue(value interface{}) gotenobject.FieldPathArrayItemValue {
	return fp.WithIArrayItemValue(value)
}

// DeploymentUpgradeState_FieldPathValue allows storing values for UpgradeState fields according to their type
type DeploymentUpgradeState_FieldPathValue interface {
	DeploymentUpgradeState_FieldPath
	gotenobject.FieldPathValue
	SetTo(target **Deployment_UpgradeState)
	CompareWith(*Deployment_UpgradeState) (cmp int, comparable bool)
}

func ParseDeploymentUpgradeState_FieldPathValue(pathStr, valueStr string) (DeploymentUpgradeState_FieldPathValue, error) {
	fp, err := ParseDeploymentUpgradeState_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpv, err := gotenobject.ParseFieldPathValue(fp, valueStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing UpgradeState field path value from %s: %v", valueStr, err)
	}
	return fpv.(DeploymentUpgradeState_FieldPathValue), nil
}

func MustParseDeploymentUpgradeState_FieldPathValue(pathStr, valueStr string) DeploymentUpgradeState_FieldPathValue {
	fpv, err := ParseDeploymentUpgradeState_FieldPathValue(pathStr, valueStr)
	if err != nil {
		panic(err)
	}
	return fpv
}

type DeploymentUpgradeState_FieldTerminalPathValue struct {
	DeploymentUpgradeState_FieldTerminalPath
	value interface{}
}

var _ DeploymentUpgradeState_FieldPathValue = (*DeploymentUpgradeState_FieldTerminalPathValue)(nil)

// GetRawValue returns raw value stored under selected path for 'UpgradeState' as interface{}
func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) GetRawValue() interface{} {
	return fpv.value
}
func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) AsTargetVersionValue() (string, bool) {
	res, ok := fpv.value.(string)
	return res, ok
}
func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) AsReadyShardsValue() ([]int64, bool) {
	res, ok := fpv.value.([]int64)
	return res, ok
}
func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) AsPendingShardsValue() ([]int64, bool) {
	res, ok := fpv.value.([]int64)
	return res, ok
}
func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) AsStageValue() (Deployment_UpgradeState_Stage, bool) {
	res, ok := fpv.value.(Deployment_UpgradeState_Stage)
	return res, ok
}

// SetTo stores value for selected field for object UpgradeState
func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) SetTo(target **Deployment_UpgradeState) {
	if *target == nil {
		*target = new(Deployment_UpgradeState)
	}
	switch fpv.selector {
	case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
		(*target).TargetVersion = fpv.value.(string)
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		(*target).ReadyShards = fpv.value.([]int64)
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		(*target).PendingShards = fpv.value.([]int64)
	case DeploymentUpgradeState_FieldPathSelectorStage:
		(*target).Stage = fpv.value.(Deployment_UpgradeState_Stage)
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fpv.selector))
	}
}

func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) SetToRaw(target proto.Message) {
	typedObject := target.(*Deployment_UpgradeState)
	fpv.SetTo(&typedObject)
}

// CompareWith compares value in the 'DeploymentUpgradeState_FieldTerminalPathValue' with the value under path in 'Deployment_UpgradeState'.
func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) CompareWith(source *Deployment_UpgradeState) (int, bool) {
	switch fpv.selector {
	case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
		leftValue := fpv.value.(string)
		rightValue := source.GetTargetVersion()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		return 0, false
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		return 0, false
	case DeploymentUpgradeState_FieldPathSelectorStage:
		leftValue := fpv.value.(Deployment_UpgradeState_Stage)
		rightValue := source.GetStage()
		if (leftValue) == (rightValue) {
			return 0, true
		} else if (leftValue) < (rightValue) {
			return -1, true
		} else {
			return 1, true
		}
	default:
		panic(fmt.Sprintf("Invalid selector for Deployment_UpgradeState: %d", fpv.selector))
	}
}

func (fpv *DeploymentUpgradeState_FieldTerminalPathValue) CompareWithRaw(source proto.Message) (int, bool) {
	return fpv.CompareWith(source.(*Deployment_UpgradeState))
}

// DeploymentUpgradeState_FieldPathArrayItemValue allows storing single item in Path-specific values for UpgradeState according to their type
// Present only for array (repeated) types.
type DeploymentUpgradeState_FieldPathArrayItemValue interface {
	gotenobject.FieldPathArrayItemValue
	DeploymentUpgradeState_FieldPath
	ContainsValue(*Deployment_UpgradeState) bool
}

// ParseDeploymentUpgradeState_FieldPathArrayItemValue parses string and JSON-encoded value to its Value
func ParseDeploymentUpgradeState_FieldPathArrayItemValue(pathStr, valueStr string) (DeploymentUpgradeState_FieldPathArrayItemValue, error) {
	fp, err := ParseDeploymentUpgradeState_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpaiv, err := gotenobject.ParseFieldPathArrayItemValue(fp, valueStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing UpgradeState field path array item value from %s: %v", valueStr, err)
	}
	return fpaiv.(DeploymentUpgradeState_FieldPathArrayItemValue), nil
}

func MustParseDeploymentUpgradeState_FieldPathArrayItemValue(pathStr, valueStr string) DeploymentUpgradeState_FieldPathArrayItemValue {
	fpaiv, err := ParseDeploymentUpgradeState_FieldPathArrayItemValue(pathStr, valueStr)
	if err != nil {
		panic(err)
	}
	return fpaiv
}

type DeploymentUpgradeState_FieldTerminalPathArrayItemValue struct {
	DeploymentUpgradeState_FieldTerminalPath
	value interface{}
}

var _ DeploymentUpgradeState_FieldPathArrayItemValue = (*DeploymentUpgradeState_FieldTerminalPathArrayItemValue)(nil)

// GetRawValue returns stored element value for array in object Deployment_UpgradeState as interface{}
func (fpaiv *DeploymentUpgradeState_FieldTerminalPathArrayItemValue) GetRawItemValue() interface{} {
	return fpaiv.value
}
func (fpaiv *DeploymentUpgradeState_FieldTerminalPathArrayItemValue) AsReadyShardsItemValue() (int64, bool) {
	res, ok := fpaiv.value.(int64)
	return res, ok
}
func (fpaiv *DeploymentUpgradeState_FieldTerminalPathArrayItemValue) AsPendingShardsItemValue() (int64, bool) {
	res, ok := fpaiv.value.(int64)
	return res, ok
}

func (fpaiv *DeploymentUpgradeState_FieldTerminalPathArrayItemValue) GetSingle(source *Deployment_UpgradeState) (interface{}, bool) {
	return nil, false
}

func (fpaiv *DeploymentUpgradeState_FieldTerminalPathArrayItemValue) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fpaiv.GetSingle(source.(*Deployment_UpgradeState))
}

// Contains returns a boolean indicating if value that is being held is present in given 'UpgradeState'
func (fpaiv *DeploymentUpgradeState_FieldTerminalPathArrayItemValue) ContainsValue(source *Deployment_UpgradeState) bool {
	slice := fpaiv.DeploymentUpgradeState_FieldTerminalPath.Get(source)
	for _, v := range slice {
		if asProtoMsg, ok := fpaiv.value.(proto.Message); ok {
			if proto.Equal(asProtoMsg, v.(proto.Message)) {
				return true
			}
		} else if reflect.DeepEqual(v, fpaiv.value) {
			return true
		}
	}
	return false
}

// DeploymentUpgradeState_FieldPathArrayOfValues allows storing slice of values for UpgradeState fields according to their type
type DeploymentUpgradeState_FieldPathArrayOfValues interface {
	gotenobject.FieldPathArrayOfValues
	DeploymentUpgradeState_FieldPath
}

func ParseDeploymentUpgradeState_FieldPathArrayOfValues(pathStr, valuesStr string) (DeploymentUpgradeState_FieldPathArrayOfValues, error) {
	fp, err := ParseDeploymentUpgradeState_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpaov, err := gotenobject.ParseFieldPathArrayOfValues(fp, valuesStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing UpgradeState field path array of values from %s: %v", valuesStr, err)
	}
	return fpaov.(DeploymentUpgradeState_FieldPathArrayOfValues), nil
}

func MustParseDeploymentUpgradeState_FieldPathArrayOfValues(pathStr, valuesStr string) DeploymentUpgradeState_FieldPathArrayOfValues {
	fpaov, err := ParseDeploymentUpgradeState_FieldPathArrayOfValues(pathStr, valuesStr)
	if err != nil {
		panic(err)
	}
	return fpaov
}

type DeploymentUpgradeState_FieldTerminalPathArrayOfValues struct {
	DeploymentUpgradeState_FieldTerminalPath
	values interface{}
}

var _ DeploymentUpgradeState_FieldPathArrayOfValues = (*DeploymentUpgradeState_FieldTerminalPathArrayOfValues)(nil)

func (fpaov *DeploymentUpgradeState_FieldTerminalPathArrayOfValues) GetRawValues() (values []interface{}) {
	switch fpaov.selector {
	case DeploymentUpgradeState_FieldPathSelectorTargetVersion:
		for _, v := range fpaov.values.([]string) {
			values = append(values, v)
		}
	case DeploymentUpgradeState_FieldPathSelectorReadyShards:
		for _, v := range fpaov.values.([][]int64) {
			values = append(values, v)
		}
	case DeploymentUpgradeState_FieldPathSelectorPendingShards:
		for _, v := range fpaov.values.([][]int64) {
			values = append(values, v)
		}
	case DeploymentUpgradeState_FieldPathSelectorStage:
		for _, v := range fpaov.values.([]Deployment_UpgradeState_Stage) {
			values = append(values, v)
		}
	}
	return
}
func (fpaov *DeploymentUpgradeState_FieldTerminalPathArrayOfValues) AsTargetVersionArrayOfValues() ([]string, bool) {
	res, ok := fpaov.values.([]string)
	return res, ok
}
func (fpaov *DeploymentUpgradeState_FieldTerminalPathArrayOfValues) AsReadyShardsArrayOfValues() ([][]int64, bool) {
	res, ok := fpaov.values.([][]int64)
	return res, ok
}
func (fpaov *DeploymentUpgradeState_FieldTerminalPathArrayOfValues) AsPendingShardsArrayOfValues() ([][]int64, bool) {
	res, ok := fpaov.values.([][]int64)
	return res, ok
}
func (fpaov *DeploymentUpgradeState_FieldTerminalPathArrayOfValues) AsStageArrayOfValues() ([]Deployment_UpgradeState_Stage, bool) {
	res, ok := fpaov.values.([]Deployment_UpgradeState_Stage)
	return res, ok
}
